// ============================================================
// Constantes partagées — copiées telles quelles depuis le
// prototype Claude (couleurs, catégories de boissons, pays...).
// ============================================================

export const COLORS = {
  paper: "#0D1B2A",
  paperAlt: "#28405C",
  surface: "#16273D",
  surfaceAlt: "#1E3350",
  ink: "#F2F2E8",
  inkSoft: "#8792A6",
  amber: "#39FF66",
  amberDark: "#2BD955",
  wine: "#E2564F",
  alert: "#E28A82",
  chalkBg: "#0D1B2A",
  chalkBgAlt: "#16273D",
  chalkWhite: "#F2F2E8",
  sage: "#2E9E6B",
  bobBlue: "#5B8FC7",
  bobYellow: "#F2C94C",
  jetonFluo: "#00C8FF",
  redFluo: "#FF3B4E",
  tabPending: "#FF7A45",
  burgundy: "#6B1F2A",
};

export const DRINK_TYPES = [
  "Bières",
  "Vins & bulles",
  "Spiritueux",
  "Cocktails / Mocktails",
  "Softs & eaux",
  "Boissons chaudes",
  "Snacks",
];

export const MENU_CATEGORIES = ["Bières", "Vins & bulles", "Spiritueux", "Shots", "Cocktails / Mocktails", "Softs & eaux", "Boissons chaudes", "Snacks"];

export const RATABLE_DRINK_TYPES = ["Bières", "Vins & bulles", "Spiritueux", "Cocktails / Mocktails"];

export const BEER_RATING_MODES = ["bouteille", "canette", "fut"];

export const COUNTRY_FLAGS = {
  Belgique: "🇧🇪",
  France: "🇫🇷",
  Luxembourg: "🇱🇺",
  Allemagne: "🇩🇪",
  "Pays-Bas": "🇳🇱",
  Algérie: "🇩🇿",
  Angleterre: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Autriche: "🇦🇹",
  Bermudes: "🇧🇲",
  Bulgarie: "🇧🇬",
  Canada: "🇨🇦",
  Chypre: "🇨🇾",
  "Côte d'Ivoire": "🇨🇮",
  Croatie: "🇭🇷",
  Cuba: "🇨🇺",
  Danemark: "🇩🇰",
  Écosse: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Espagne: "🇪🇸",
  Estonie: "🇪🇪",
  "États-Unis": "🇺🇸",
  Finlande: "🇫🇮",
  Grèce: "🇬🇷",
  Hongrie: "🇭🇺",
  Irlande: "🇮🇪",
  Islande: "🇮🇸",
  Italie: "🇮🇹",
  Japon: "🇯🇵",
  Lettonie: "🇱🇻",
  Lituanie: "🇱🇹",
  Malte: "🇲🇹",
  Maroc: "🇲🇦",
  Mexique: "🇲🇽",
  Norvège: "🇳🇴",
  Pologne: "🇵🇱",
  Portugal: "🇵🇹",
  "République tchèque": "🇨🇿",
  Roumanie: "🇷🇴",
  "Royaume-Uni": "🇬🇧",
  Sénégal: "🇸🇳",
  Slovaquie: "🇸🇰",
  Slovénie: "🇸🇮",
  Suède: "🇸🇪",
  Suisse: "🇨🇭",
  Tunisie: "🇹🇳",
  Vénézuéla: "🇻🇪",
};

export const CITIES_BY_COUNTRY = {
  Belgique: [
    "Waimes",
    "Malmedy",
    "Bütgenbach",
    "Stavelot",
    "Robertville",
    "Ovifat",
    "Weismes",
    "Sourbrodt",
    "Faymonville",
    "Ligneuville",
    "Longfaye",
    "Eupen",
    "Saint-Vith",
    "Spa",
    "Verviers",
    "Trois-Ponts",
    "Vielsalm",
    "Bastogne",
    "Liège",
    "Huy",
    "Waremme",
    "Seraing",
    "Herstal",
    "Namur",
    "Dinant",
    "Ciney",
    "Rochefort",
    "Marche-en-Famenne",
    "La Roche-en-Ardenne",
    "Durbuy",
    "Charleroi",
    "Mons",
    "Tournai",
    "La Louvière",
    "Mouscron",
    "Ath",
    "Nivelles",
    "Wavre",
    "Ottignies-Louvain-la-Neuve",
    "Braine-l'Alleud",
    "Bruxelles",
    "Ixelles",
    "Schaerbeek",
    "Uccle",
    "Anderlecht",
    "Etterbeek",
    "Woluwe-Saint-Lambert",
    "Anvers",
    "Gand",
    "Bruges",
    "Louvain",
    "Malines",
    "Ostende",
    "Courtrai",
    "Hasselt",
    "Genk",
    "Roulers",
    "Turnhout",
    "Alost",
    "Saint-Nicolas",
  ],
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Saint-Étienne",
    "Toulon",
    "Le Havre",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Clermont-Ferrand",
    "Le Mans",
    "Aix-en-Provence",
    "Brest",
    "Tours",
    "Amiens",
    "Limoges",
    "Annecy",
    "Metz",
    "Besançon",
    "Perpignan",
    "Orléans",
    "Rouen",
    "Mulhouse",
    "Caen",
    "Nancy",
    "Avignon",
    "Sedan",
    "Charleville-Mézières",
    "Givet",
  ],
  Luxembourg: [
    "Luxembourg",
    "Esch-sur-Alzette",
    "Differdange",
    "Dudelange",
    "Ettelbruck",
    "Diekirch",
    "Wiltz",
    "Echternach",
    "Rumelange",
    "Grevenmacher",
    "Remich",
    "Vianden",
    "Clervaux",
  ],
  Allemagne: [
    "Berlin",
    "Hambourg",
    "Munich",
    "Cologne",
    "Francfort",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Brême",
    "Dresde",
    "Hanovre",
    "Nuremberg",
    "Aix-la-Chapelle",
    "Trèves",
    "Sarrebruck",
    "Bonn",
    "Mannheim",
    "Wiesbaden",
  ],
  "Pays-Bas": [
    "Amsterdam",
    "Rotterdam",
    "La Haye",
    "Utrecht",
    "Eindhoven",
    "Groningue",
    "Tilburg",
    "Almere",
    "Breda",
    "Nimègue",
    "Maastricht",
    "Arnhem",
    "Haarlem",
    "Enschede",
    "Amersfoort",
    "Leyde",
    "Zwolle",
    "Venlo",
    "Roosendaal",
  ],
  Algérie: ["Alger", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Sétif", "Sidi Bel Abbès", "Tlemcen"],
  Autriche: ["Vienne", "Graz", "Linz", "Salzbourg", "Innsbruck", "Klagenfurt", "Villach", "Wels"],
  Bulgarie: ["Sofia", "Plovdiv", "Varna", "Burgas", "Roussé"],
  Canada: ["Toronto", "Montréal", "Vancouver", "Ottawa", "Calgary", "Edmonton", "Québec", "Winnipeg"],
  Chypre: ["Nicosie", "Limassol", "Larnaca", "Paphos", "Famagouste"],
  "Côte d'Ivoire": ["Abidjan", "Bouaké", "Yamoussoukro", "San-Pédro", "Korhogo"],
  Croatie: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Dubrovnik"],
  Danemark: ["Copenhague", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  Espagne: ["Madrid", "Barcelone", "Valence", "Séville", "Saragosse", "Malaga", "Murcie", "Bilbao", "Alicante", "Palma"],
  Estonie: ["Tallinn", "Tartu", "Narva", "Pärnu"],
  "États-Unis": ["New York", "Los Angeles", "Chicago", "Houston", "Miami", "San Francisco", "Boston", "Washington", "Seattle", "Las Vegas"],
  Finlande: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Turku", "Oulu"],
  Grèce: ["Athènes", "Thessalonique", "Patras", "Héraklion", "Larissa"],
  Hongrie: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
  Irlande: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  Islande: ["Reykjavik", "Kópavogur", "Akureyri"],
  Italie: ["Rome", "Milan", "Naples", "Turin", "Palerme", "Gênes", "Bologne", "Florence", "Venise", "Vérone"],
  Lettonie: ["Riga", "Daugavpils", "Liepāja"],
  Lituanie: ["Vilnius", "Kaunas", "Klaipėda"],
  Malte: ["La Valette", "Birkirkara", "Mosta", "Sliema"],
  Maroc: ["Casablanca", "Rabat", "Fès", "Marrakech", "Tanger", "Agadir", "Meknès", "Oujda"],
  Norvège: ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  Pologne: ["Varsovie", "Cracovie", "Łódź", "Wrocław", "Poznań", "Gdańsk"],
  Portugal: ["Lisbonne", "Porto", "Braga", "Coimbra", "Faro"],
  "République tchèque": ["Prague", "Brno", "Ostrava", "Plzeň"],
  Roumanie: ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  "Royaume-Uni": ["Londres", "Manchester", "Birmingham", "Glasgow", "Édimbourg", "Liverpool", "Leeds", "Bristol"],
  Sénégal: ["Dakar", "Thiès", "Rufisque", "Kaolack", "Saint-Louis"],
  Slovaquie: ["Bratislava", "Košice", "Prešov"],
  Slovénie: ["Ljubljana", "Maribor", "Celje"],
  Suède: ["Stockholm", "Göteborg", "Malmö", "Uppsala"],
  Suisse: ["Genève", "Zurich", "Berne", "Bâle", "Lausanne", "Lucerne", "Lugano", "Fribourg"],
  Tunisie: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
};

export const DRINK_CATEGORY_ICONS = {
  Bières: "🍺",
  "Vins & bulles": "🍷",
  Spiritueux: "🥃",
  "Cocktails / Mocktails": "🍸",
  Shots: "🍶",
  "Softs & eaux": "💧",
  "Boissons chaudes": "☕",
  Snacks: "🥨",
};

export const DRINK_TYPE_MIGRATIONS = {
  "Bière pils": "Bières",
  "Bière spéciales": "Bières",
  Bière: "Bières",
  "Vin & bulles": "Vins & bulles",
  Alcools: "Spiritueux",
  Cocktails: "Cocktails / Mocktails",
  Shooters: "Spiritueux",
  Shots: "Spiritueux",
  Eau: "Softs & eaux",
  Soft: "Softs & eaux",
  "Boisson chaude": "Boissons chaudes",
  Snack: "Snacks",
};

export const NON_ALCOHOLIC_DRINK_TYPES = ["Softs & eaux", "Boissons chaudes", "Snacks"];
export const GLUTEN_BIO_ELIGIBLE_TYPES = ["Bières"];

export const NATIONALITY_ELIGIBLE_TYPES = ["Bières", "Vins & bulles", "Spiritueux", "Softs & eaux", "Boissons chaudes"];

export const DRINK_VOLUMES_CL = [2, 2.5, 3, 3.5, 4, 4.5, 5, 6, 7, 8, 9, 10, 12, 12.5, 15, 17, 18, 20, 22, 25, 28, 30, 33, 35, 40, 50, 66, 70, 75, 100, 120, 150, 200, 300];

export const SNACK_WEIGHTS_G = [25, 40, 45, 50, 75, 100, 125, 150, 200, 250, 300, 400, 500];

export const BEER_TYPES = ["Bières"];

export const SERVING_MODE_LABELS = { bouteille: "Bouteille", canette: "Canette", verre: "Au verre", fut: "On tap" };

export const BEER_STYLE_TAGS = [
  "Blonde",
  "Blonde dorée",
  "Ambrée",
  "Rousse",
  "Brune",
  "Noire",
  "Blanche",
  "Rouge",
  "Rubis",
  "Pils",
  "Fruitée",
  "Lager blonde",
  "Export",
  "Session Lager",
  "Pale Lager",
  "Bière de table",
  "Sans alcool",
  "Faible en alcool",
  "Bière légère",
  "Low calories",
  "Blonde belge",
  "Bière forte",
  "Blonde forte",
  "Brune forte",
  "Fruitée forte",
  "Spéciale belge",
  "Bière d'Abbaye",
  "Bière Trappiste",
  "Double",
  "Triple",
  "Quadrupel",
  "Belgian Strong Ale",
  "Dark Strong Ale",
  "Saison",
  "Bière de garde",
  "Bière brut",
  "Bière de Noël",
  "Bière estivale",
  "Bière d'Hiver",
  "Bière de récolte",
  "Weissbier",
  "Gose",
  "Amber Ale",
  "Porter",
  "Stout",
  "Irish Dry Stout",
  "Chocolate Stout",
  "Black IPA",
  "Pale Ale",
  "Hoppy Pale Ale",
  "IPA",
  "New England IPA",
  "Hazy IPA",
  "Sour IPA",
  "Pilsner",
  "Lambic",
  "Gueuze",
  "Kriek",
  "Cerise",
  "Framboise",
  "Pêche",
  "Faro",
  "Biologique",
  "Sans gluten",
  "Premium",
];

export const SOFT_DRINK_TAGS = [
  "Soda",
  "Cola",
  "Limonade",
  "Orangeade",
  "Tonic",
  "Thé glacé",
  "Jus de fruits",
  "Boissons énergisantes",
  "Light",
  "Zero",
  "Pétillant",
  "Fortement pétillant",
  "Non-pétillant",
  "Ginger Ale",
  "Ginger Beer",
  "Sirop",
  "Aromatisé",
  "Bio",
  "Caféiné",
  "Sans caféine",
  "Végane",
];

export const SPIRIT_TAGS = ["Vodka", "Whisky", "Gin", "Rhum", "Tequila"];

export const WINE_TAGS = ["Sec", "Demi-sec", "Doux"];

export const SNACK_TYPES = [
  "Barre chocolatée",
  "Boulette",
  "Burger",
  "Chips",
  "Coupelle",
  "Croque",
  "Finger Food",
  "Friture",
  "Gaufre",
  "Glace",
  "Hot-dog",
  "Nachos",
  "Panini",
  "Pâtes",
  "Pizza",
  "Planche apéro",
  "Sandwich",
  "Saucisse",
  "Saucisson",
  "Tapas",
  "Végétarien",
];

export const VENUE_TYPE_TAGS = [
  "Bar",
  "Café",
  "Taverne",
  "Bistrot",
  "Estaminet",
  "Café de quartier",
  "Brasserie",
  "Cafétaria",
  "Buvette",
  "Bar d'hôtel",
  "Microbrasserie",
  "Restaurant",
  "Salle de spectacle",
  "Salle de concert",
  "Salle de location",
  "Bar lounge",
  "Bar-concert",
  "Bar e-sport",
  "Bar à bières",
  "Bar à vins",
  "Bar à champagne",
  "Bar à cocktails",
  "Bar à rhum",
  "Bar à whiskey",
  "Bar à gin",
  "Bar à shots",
  "Bar à jeux",
  "Piano-Bar",
  "Karaoké-Bar",
  "Bar dansant",
  "Discothèque",
  "Night-club",
  "Cabaret",
  "Club privé",
  "Pub",
  "Irish pub",
  "Terrasse",
  "Grande terrasse",
  "Rooftop",
];

export const COUNTRIES = [
  "Belgique",
  "France",
  "Luxembourg",
  "Allemagne",
  "Pays-Bas",
  "Algérie",
  "Autriche",
  "Bulgarie",
  "Canada",
  "Chypre",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Espagne",
  "Estonie",
  "États-Unis",
  "Finlande",
  "Grèce",
  "Hongrie",
  "Irlande",
  "Islande",
  "Italie",
  "Lettonie",
  "Lituanie",
  "Malte",
  "Maroc",
  "Mexique",
  "Norvège",
  "Pologne",
  "Portugal",
  "République tchèque",
  "Roumanie",
  "Royaume-Uni",
  "Sénégal",
  "Slovaquie",
  "Slovénie",
  "Suède",
  "Suisse",
  "Tunisie",
  "Vénézuéla",
  "Autre",
];


export const GENERIC_BRAND_LABEL = "Autre marque";

export const EVENT_MODE_LABELS = {
  tournees: "ORBIS",
  cagnotte: "ARCA",
  addition: "PARTES",
  openbar: "LIBER",
};
export const EVENT_MODE_DESC = {
  tournees: "Tournées",
  cagnotte: "Cagnotte",
  addition: "Addition partagée",
  openbar: "Open bar",
};

export const VOLUME_DISPLAY_TYPES = ["Bières", "Softs & eaux"];


export const DRINK_FIELD_LABELS = {
  name: "Nom complet du produit",
  type: "Type",
  kcalPer100ml: "Calories (pour 100ml)",
  beerTags: "Style & caractéristiques",
  abv: "Degré d'alcool",
  brand: "Marque du produit",
  brewery: "Producteur",
  nationality: "Pays d'origine de la marque",
  glutenFree: "Sans gluten",
  bio: "Label Bio",
  volumeCl: "Volume par défaut",
  servingMode: "Type de service par défaut",
  snackType: "Type de produit",
  weightG: "Poids par défaut",
  isGeneric: "Produit générique",
  averagePrice: "Prix indicatif",
  countsAsDrinkId: "Compte comme",
  description: "Description",
};
export const MONTH_NAMES_FR = ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"];

export const ADMIN_PASSPHRASE = "bibamus-admin"; // Mehdi: change this string any time you want a new passphrase.

export const AVATAR_EMOJIS = ["👤", "🍺", "🍷", "🥂", "🍸", "🥃", "🍾", "🎉", "🎊", "🌙", "⭐", "🔥"];
export const LANGUAGES = [{ code: "fr", label: "Français" }];

export const BREWERY_FIELD_LABELS = { name: "Nom", country: "Pays d'origine" };
export const BRAND_FIELD_LABELS = { name: "Nom" };
export const WEEKDAY_SHORT_MON_FIRST = ["L", "M", "M", "J", "V", "S", "D"];

// À incrémenter à chaque mise à jour envoyée — permet de vérifier d'un coup d'œil qu'un
// déploiement a bien pris effet, plutôt que de deviner face à un souci de cache.
export const APP_VERSION = "26.27";
