export const COUNTRIES = [
  { code: "belgique", fr: "Belgique" },
  { code: "france", fr: "France" },
  { code: "pays_bas", fr: "Pays-Bas" },
  { code: "allemagne", fr: "Allemagne" },
  { code: "luxembourg", fr: "Luxembourg" },
  { code: "algerie", fr: "Algérie" },
  { code: "autriche", fr: "Autriche" },
  { code: "bulgarie", fr: "Bulgarie" },
  { code: "canada", fr: "Canada" },
  { code: "chypre", fr: "Chypre" },
  { code: "cote_d_ivoire", fr: "Côte d'Ivoire" },
  { code: "croatie", fr: "Croatie" },
  { code: "cuba", fr: "Cuba" },
  { code: "danemark", fr: "Danemark" },
  { code: "espagne", fr: "Espagne" },
  { code: "estonie", fr: "Estonie" },
  { code: "etats_unis", fr: "États-Unis" },
  { code: "finlande", fr: "Finlande" },
  { code: "grece", fr: "Grèce" },
  { code: "hongrie", fr: "Hongrie" },
  { code: "irlande", fr: "Irlande" },
  { code: "islande", fr: "Islande" },
  { code: "italie", fr: "Italie" },
  { code: "lettonie", fr: "Lettonie" },
  { code: "lituanie", fr: "Lituanie" },
  { code: "malte", fr: "Malte" },
  { code: "maroc", fr: "Maroc" },
  { code: "mexique", fr: "Mexique" },
  { code: "norvege", fr: "Norvège" },
  { code: "pologne", fr: "Pologne" },
  { code: "portugal", fr: "Portugal" },
  { code: "republique_tcheque", fr: "République tchèque" },
  { code: "roumanie", fr: "Roumanie" },
  { code: "royaume_uni", fr: "Royaume-Uni" },
  { code: "senegal", fr: "Sénégal" },
  { code: "slovaquie", fr: "Slovaquie" },
  { code: "slovenie", fr: "Slovénie" },
  { code: "suede", fr: "Suède" },
  { code: "suisse", fr: "Suisse" },
  { code: "tunisie", fr: "Tunisie" },
  { code: "venezuela", fr: "Vénézuéla" },
  { code: "autre", fr: "Autre" },
];

export const PAYMENT_METHODS = [
  { code: "especes", fr: "Espèces" },
  { code: "carte_bancaire", fr: "Carte bancaire" },
  { code: "sans_contact", fr: "Sans contact" },
  { code: "bancontact", fr: "Bancontact" },
  { code: "payconiq", fr: "Payconiq" },
  { code: "virement", fr: "Virement" },
  { code: "cheque", fr: "Chèque" },
];

export const VENUE_TYPES = [
  { code: "bar", fr: "Bar" },
  { code: "cafe", fr: "Café" },
  { code: "taverne", fr: "Taverne" },
  { code: "bistrot", fr: "Bistrot" },
  { code: "pub", fr: "Pub" },
  { code: "estaminet", fr: "Estaminet" },
  { code: "cafe_de_quartier", fr: "Café de quartier" },
  { code: "brasserie", fr: "Brasserie" },
  { code: "restaurant", fr: "Restaurant" },
  { code: "brasserie_restaurant", fr: "Brasserie-Restaurant" },
  { code: "irish_pub", fr: "Irish Pub" },
  { code: "cafetaria", fr: "Cafétaria" },
  { code: "buvette", fr: "Buvette" },
  { code: "bar_d_hotel", fr: "Bar d'hôtel" },
  { code: "microbrasserie", fr: "Microbrasserie" },
  { code: "salle_de_spectacle", fr: "Salle de spectacle" },
  { code: "salle_de_concert", fr: "Salle de concert" },
  { code: "salle_de_location", fr: "Salle de location" },
  { code: "bar_lounge", fr: "Bar lounge" },
  { code: "bar_concert", fr: "Bar-concert" },
  { code: "piano_bar", fr: "Piano bar" },
  { code: "karaoke_bar", fr: "Karaoké bar" },
  { code: "bar_dansant", fr: "Bar dansant" },
  { code: "discotheque", fr: "Discothèque" },
  { code: "cabaret", fr: "Cabaret" },
  { code: "club_prive", fr: "Club privé" },
  { code: "bar_e_sport", fr: "Bar e-sport" },
  { code: "bar_a_jeux_electroniques", fr: "Bar à jeux électroniques" },
  { code: "bar_a_jeux_d_arcade", fr: "Bar à jeux d'arcade" },
  { code: "bar_a_jeux_de_societe", fr: "Bar à jeux de société" },
  { code: "bowling", fr: "Bowling" },
  { code: "terrasse", fr: "Terrasse" },
  { code: "grande_terrasse", fr: "Grande terrasse" },
  { code: "rooftop", fr: "Rooftop" },
  { code: "bar_a_bieres", fr: "Bar à bières" },
  { code: "bar_a_vins", fr: "Bar à vins" },
  { code: "bar_a_champagne", fr: "Bar à champagne" },
  { code: "bar_a_cocktails", fr: "Bar à cocktails" },
  { code: "bar_a_rhum", fr: "Bar à rhum" },
  { code: "bar_a_whiskey", fr: "Bar à whiskey" },
  { code: "bar_a_gin", fr: "Bar à gin" },
  { code: "bar_a_shot", fr: "Bar à shot" },
];

export const PHONE_PREFIXES = {
  belgique: "+32",
  france: "+33",
  pays_bas: "+31",
  allemagne: "+49",
  luxembourg: "+352",
  algerie: "+213",
  autriche: "+43",
  bulgarie: "+359",
  canada: "+1",
  chypre: "+357",
  cote_d_ivoire: "+225",
  croatie: "+385",
  cuba: "+53",
  danemark: "+45",
  espagne: "+34",
  estonie: "+372",
  etats_unis: "+1",
  finlande: "+358",
  grece: "+30",
  hongrie: "+36",
  irlande: "+353",
  islande: "+354",
  italie: "+39",
  lettonie: "+371",
  lituanie: "+370",
  malte: "+356",
  maroc: "+212",
  mexique: "+52",
  norvege: "+47",
  pologne: "+48",
  portugal: "+351",
  republique_tcheque: "+420",
  roumanie: "+40",
  royaume_uni: "+44",
  senegal: "+221",
  slovaquie: "+421",
  slovenie: "+386",
  suede: "+46",
  suisse: "+41",
  tunisie: "+216",
  venezuela: "+58",
  autre: ""
};

export const PRODUCER_TYPES = [
  { code: "brasserie", fr: "Brasserie" },
  { code: "micro_brasserie", fr: "Micro-brasserie" },
  { code: "distillerie", fr: "Distillerie" },
  { code: "cidrerie", fr: "Cidrerie" },
  { code: "domaine_viticole", fr: "Domaine viticole" },
  { code: "hydromellerie", fr: "Hydromellerie" },
  { code: "torrefacteur", fr: "Torréfacteur" },
  { code: "boissons_sans_alcool", fr: "Boissons sans alcool" },
  { code: "alimentaire", fr: "Alimentaire" },
];

export const PRODUCER_PROFILES = [
  { code: "micro_producteur", fr: "Micro-producteur" },
  { code: "artisanal", fr: "Artisanal" },
  { code: "local", fr: "Local" },
  { code: "independant", fr: "Indépendant" },
  { code: "industriel", fr: "Industriel" },
  { code: "groupe", fr: "Groupe" },
  { code: "multinationale", fr: "Multinationale" },
  { code: "cooperative", fr: "Coopérative" },
];

export const BRAND_CLASSIFICATIONS = [
  { code: "biere", fr: "Bière" },
  { code: "vin", fr: "Vin" },
  { code: "spiritueux", fr: "Spiritueux" },
  { code: "cidre", fr: "Cidre" },
  { code: "soft_soda", fr: "Soft / Soda" },
  { code: "eau", fr: "Eau" },
  { code: "boisson_energetique", fr: "Boisson énergétique" },
  { code: "cafe", fr: "Café" },
  { code: "the", fr: "Thé" },
  { code: "snack_sale", fr: "Snack salé" },
  { code: "snack_sucre", fr: "Snack sucré" },
  { code: "autre", fr: "Autre" },
];

export const BRAND_TYPES = [
  { code: "artisanale", fr: "Artisanale" },
  { code: "locale", fr: "Locale" },
  { code: "regionale", fr: "Régionale" },
  { code: "nationale", fr: "Nationale" },
  { code: "internationale", fr: "Internationale" },
];
